### 1. 

En el archivo "logistic_regression_df_class" hemos visto un ejemplo multiclase. Elimina del dataframe todas las filas que se correspondan con la clase valor "1".

Ahora, realiza el ejercicio con el nuevo dataframe:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
dataframe = pd.read_csv("../data/usuarios_win_mac_lin.csv")

In [3]:
dataframe

duracion  paginas  acciones  valor  clase
0         7.0        2         4      8      2
1        21.0        2         6      6      2
2        57.0        2         4      4      2
3       101.0        3         6     12      2
4       109.0        2         6     12      2
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[170 rows x 5 columns]

In [4]:
dataframe.clase.value_counts()

0    86
2    44
1    40
Name: clase, dtype: int64

In [6]:
dataframe = dataframe.drop(dataframe[dataframe.clase == 1].index)

In [7]:
dataframe.clase.value_counts()

0    86
2    44
Name: clase, dtype: int64

In [8]:
X = np.array(dataframe.drop(['clase'], axis=1))
y = np.array(dataframe['clase'])
print(y.shape)
X.shape

(130,)


(130, 4)

### PROBANDO SIN CLASES

In [10]:
model = linear_model.LogisticRegression()

model.fit(X,y)

LogisticRegression()

In [11]:
predictions = model.predict(X)
print(predictions)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0
 2 0 0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0]


In [12]:
model.score(X,y)

0.9538461538461539

### Validacion del Modelo

In [13]:
seed = 7 # le estoy dando una semilla 7 
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(104, 4)


(26, 4)

In [14]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed, shuffle=True)
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results) 
print("----------")
print(msg) 
print("----------")
print("----------")

[1.         0.90909091 0.90909091 0.90909091 1.         0.8
 1.         1.         0.9        0.8       ]
----------
Logistic Regression: 0.922727 +- (0.074218)
----------
----------


In [15]:
model.score(X_test, Y_test)

0.9615384615384616

In [16]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.9615384615384616
0.9615384615384616


In [17]:
# Otra forma de calcular
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 96.15 %
Error: 3.85 %


In [18]:
print(confusion_matrix(Y_test, predictions))

[[22  1]
 [ 0  3]]


### PROBANDO CON VARIOS ARGUMENTOS

In [41]:
dataframe = dataframe.drop(dataframe[dataframe.clase == 1].index)

In [42]:
X = np.array(dataframe.drop(['clase'], axis=1))
y = np.array(dataframe['clase'])
print(y.shape)
X.shape

(130,)


(130, 4)

In [32]:
model = linear_model.LogisticRegression(max_iter=300, tol=0.80, C=9, solver="liblinear")

model.fit(X,y)

LogisticRegression(C=9, max_iter=300, solver='liblinear', tol=0.8)

In [33]:
predictions = model.predict(X)
print(predictions)

[0 0 0 0 0 0 2 0 2 2 2 0 2 2 2 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 2 2 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [34]:
model.score(X,y)

0.7076923076923077

In [35]:
seed = 7 # le estoy dando una semilla 7 
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(104, 4)


(26, 4)

In [36]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed, shuffle=True)
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results) 
print("----------")
print(msg) 
print("----------")
print("----------")

[0.72727273 0.63636364 0.63636364 0.81818182 0.4        0.6
 0.5        0.8        0.8        0.6       ]
----------
Logistic Regression: 0.651818 +- (0.130229)
----------
----------


In [37]:
model.score(X_test, Y_test)

0.8076923076923077

In [38]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.8076923076923077
0.8076923076923077


In [39]:
# Otra forma de calcular
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 80.77 %
Error: 19.23 %


In [40]:
print(confusion_matrix(Y_test, predictions))

[[21  2]
 [ 3  0]]


### PROBANDO OTROS ARGUMENTOS

In [52]:
dataframe = dataframe.drop(dataframe[dataframe.clase == 1].index)

In [53]:
X = np.array(dataframe.drop(['clase'], axis=1))
y = np.array(dataframe['clase'])
print(y.shape)
X.shape

(130,)


(130, 4)

In [54]:
model = linear_model.LogisticRegression(max_iter=999, tol=0.75, C=9)

model.fit(X,y)

LogisticRegression(C=9, max_iter=999, tol=0.75)

In [55]:
predictions = model.predict(X)
print(predictions)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 2 0 0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0]


In [56]:
model.score(X,y)

0.9615384615384616

In [57]:
seed = 7 # le estoy dando una semilla 7 
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(104, 4)


(26, 4)

In [58]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed, shuffle=True)
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results) 
print("----------")
print(msg) 
print("----------")
print("----------")

[1.         0.90909091 1.         0.90909091 1.         0.8
 1.         1.         0.9        0.8       ]
----------
Logistic Regression: 0.931818 +- (0.077486)
----------
----------


In [59]:
model.score(X_test, Y_test)

1.0

In [49]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

1.0
1.0


In [50]:
# Otra forma de calcular
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 100.0 %
Error: 0.0 %


In [51]:
print(confusion_matrix(Y_test, predictions))

[[23  0]
 [ 0  3]]


### RESULTADOS

#### Cuando se elimina una de las clases no se observa que mejore la precision del algoritmo, es mas, se observa que este empeora. Sin embargo al modificar ciertos parametros se observa que mejora el porcentaje de acierto del problema cuando se aumentan mas parámetros, con relacion a la regresion que no presenta ningun parámetro.  



