In [1]:

import numpy as np
import pandas as pd
import urllib.request
from PIL import Image
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectKBest
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_log_error, mean_squared_error, r2_score, mean_absolute_error
import math



import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
diamonds = pd.read_csv("diamonds_train.csv", index_col=0)

In [3]:
diamonds

carat        cut color clarity  depth  table     x     y     z  price
0       1.21      Ideal     H     VS2   63.0   57.0  6.73  6.70  4.23   6134
1       0.28  Very Good     D    VVS2   64.0   56.0  4.14  4.17  2.66    532
2       0.42    Premium     F     VS1   61.2   58.0  4.86  4.82  2.96   1103
3       0.26      Ideal     H      IF   61.1   57.0  4.16  4.12  2.53    600
4       1.10       Good     G     SI1   63.4   57.0  6.52  6.55  4.14   4997
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
40340   1.55    Premium     H     VS2   61.3   61.0  7.46  7.39  4.55  11708
40341   0.36      Ideal     D     SI1   60.6   56.0  4.58  4.63  2.79    619
40342   0.57  Very Good     I     VS2   62.2   55.0  5.33  5.34  3.32   1267
40343   1.01  Very Good     F      IF   59.6   62.0  6.47  6.56  3.88   9965
40344   0.54      Ideal     E     SI2   60.4   57.0  5.33  5.27  3.20   1340

[40345 rows x 10 columns]

In [4]:
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40345 entries, 0 to 40344
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    40345 non-null  float64
 1   cut      40345 non-null  object 
 2   color    40345 non-null  object 
 3   clarity  40345 non-null  object 
 4   depth    40345 non-null  float64
 5   table    40345 non-null  float64
 6   x        40345 non-null  float64
 7   y        40345 non-null  float64
 8   z        40345 non-null  float64
 9   price    40345 non-null  int64  
dtypes: float64(6), int64(1), object(3)
memory usage: 3.4+ MB


In [5]:
diamonds.clarity.unique()

array(['VS2', 'VVS2', 'VS1', 'IF', 'SI1', 'SI2', 'VVS1', 'I1'],
      dtype=object)

In [7]:
#Poner una categoria de mayor valor al clarity
diamonds_df = diamonds.copy()
diamonds_df["clarity_value"] = diamonds_df["clarity"].map({'I1': 1, 'SI2': 2, 'SI1': 3, 'VS2':4, 'VS1':5, 'VVS2':6, 'VVS1':7, 'IF':8 })
diamonds_df

carat        cut color clarity  depth  table     x     y     z  price  \
0       1.21      Ideal     H     VS2   63.0   57.0  6.73  6.70  4.23   6134   
1       0.28  Very Good     D    VVS2   64.0   56.0  4.14  4.17  2.66    532   
2       0.42    Premium     F     VS1   61.2   58.0  4.86  4.82  2.96   1103   
3       0.26      Ideal     H      IF   61.1   57.0  4.16  4.12  2.53    600   
4       1.10       Good     G     SI1   63.4   57.0  6.52  6.55  4.14   4997   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...   
40340   1.55    Premium     H     VS2   61.3   61.0  7.46  7.39  4.55  11708   
40341   0.36      Ideal     D     SI1   60.6   56.0  4.58  4.63  2.79    619   
40342   0.57  Very Good     I     VS2   62.2   55.0  5.33  5.34  3.32   1267   
40343   1.01  Very Good     F      IF   59.6   62.0  6.47  6.56  3.88   9965   
40344   0.54      Ideal     E     SI2   60.4   57.0  5.33  5.27  3.20   1340   

       clarity_value  
0                  4  
1                  6  
2                  5  
3                  8  
4                  3  
...              ...  
40340              4  
40341              3  
40342              4  
40343              8  
40344              2  

[40345 rows x 11 columns]

In [8]:
diamonds.color.unique()

array(['H', 'D', 'F', 'G', 'I', 'E', 'J'], dtype=object)

In [9]:
#Poner una categoria de mayor valor al color
diamonds_df["color_value"] = diamonds_df["color"].map({'J': 1, 'I': 2, 'H': 3, 'G':4, 'F':5, 'E':6, 'D':7})
diamonds_df

carat        cut color clarity  depth  table     x     y     z  price  \
0       1.21      Ideal     H     VS2   63.0   57.0  6.73  6.70  4.23   6134   
1       0.28  Very Good     D    VVS2   64.0   56.0  4.14  4.17  2.66    532   
2       0.42    Premium     F     VS1   61.2   58.0  4.86  4.82  2.96   1103   
3       0.26      Ideal     H      IF   61.1   57.0  4.16  4.12  2.53    600   
4       1.10       Good     G     SI1   63.4   57.0  6.52  6.55  4.14   4997   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...   
40340   1.55    Premium     H     VS2   61.3   61.0  7.46  7.39  4.55  11708   
40341   0.36      Ideal     D     SI1   60.6   56.0  4.58  4.63  2.79    619   
40342   0.57  Very Good     I     VS2   62.2   55.0  5.33  5.34  3.32   1267   
40343   1.01  Very Good     F      IF   59.6   62.0  6.47  6.56  3.88   9965   
40344   0.54      Ideal     E     SI2   60.4   57.0  5.33  5.27  3.20   1340   

       clarity_value  color_value  
0                  4            3  
1                  6            7  
2                  5            5  
3                  8            3  
4                  3            4  
...              ...          ...  
40340              4            3  
40341              3            7  
40342              4            2  
40343              8            5  
40344              2            6  

[40345 rows x 12 columns]

In [10]:
diamonds.cut.unique()

array(['Ideal', 'Very Good', 'Premium', 'Good', 'Fair'], dtype=object)

In [11]:
#Poner una categoria de mayor valor al corte
diamonds_df["cut_value"] = diamonds_df["cut"].map({'Fair': 1, 'Good': 2, 'Very Good': 3, 'Premium':4, 'Ideal':5})
diamonds_df

carat        cut color clarity  depth  table     x     y     z  price  \
0       1.21      Ideal     H     VS2   63.0   57.0  6.73  6.70  4.23   6134   
1       0.28  Very Good     D    VVS2   64.0   56.0  4.14  4.17  2.66    532   
2       0.42    Premium     F     VS1   61.2   58.0  4.86  4.82  2.96   1103   
3       0.26      Ideal     H      IF   61.1   57.0  4.16  4.12  2.53    600   
4       1.10       Good     G     SI1   63.4   57.0  6.52  6.55  4.14   4997   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...   
40340   1.55    Premium     H     VS2   61.3   61.0  7.46  7.39  4.55  11708   
40341   0.36      Ideal     D     SI1   60.6   56.0  4.58  4.63  2.79    619   
40342   0.57  Very Good     I     VS2   62.2   55.0  5.33  5.34  3.32   1267   
40343   1.01  Very Good     F      IF   59.6   62.0  6.47  6.56  3.88   9965   
40344   0.54      Ideal     E     SI2   60.4   57.0  5.33  5.27  3.20   1340   

       clarity_value  color_value  cut_value  
0                  4            3          5  
1                  6            7          3  
2                  5            5          4  
3                  8            3          5  
4                  3            4          2  
...              ...          ...        ...  
40340              4            3          4  
40341              3            7          5  
40342              4            2          3  
40343              8            5          3  
40344              2            6          5  

[40345 rows x 13 columns]

In [ ]:
#### de acuerdo al mercado Diamantes blancos con un mínimo de 1 quilate de color G, pureza VS2 y un corte de buena calidad son la mejor opción. El precio para estos diamantes aumentará en los próximos años.

### 1. Definir X e y

In [12]:
X = np.array(diamonds_df[['carat','x','y','z', 'clarity_value', 'color_value', 'cut_value' ]])
y = np.array(diamonds_df['price'])
X.shape

(40345, 7)

### 2. Dividir X_train, X_test, y_train, y_test

In [13]:
# el test_size 0.20 y el random state puede cambiar 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [14]:
models = {
    "Linear_Regression": LinearRegression(),
    "Random_Forest": RandomForestRegressor(),
    "DecisionTreeRegresor": DecisionTreeRegressor(),
    "KNeighbors": KNeighborsRegressor(),
    "GradientBooster": GradientBoostingRegressor(),
}

In [21]:
def train_model(X_train, y_train, model, X_test, y_test):
    clf = model
    clf.fit(X_train, y_train)
    accuracies = cross_val_score(
        estimator=clf, X=X_train, y=y_train, cv=5, verbose=1)
    y_pred = clf.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred)**0.5
    r2 = r2_score(y_test, y_pred)
    score = clf.score(X_test, y_test)
    return (mae, mse, rmse, r2, y_pred, accuracies, score)

In [22]:
for label, model in models.items():
    mae, mse, rmse, r2, y_pred, accuracies, score = train_model(
        X_train, y_train, model, X_test, y_test)
    print('')
    print('####### {} #######'.format(label))
    print('Score : %.4f' % score)
    print(accuracies)
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %f ' % r2)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

####### Linear_Regression #######
Score : 0.9103
[0.90754509 0.90947511 0.91191012 0.90060908 0.90902866]

MSE    : 1424573.50 
MAE    : 803.67 
RMSE   : 1193.55 
R2     : 0.910339 
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   33.7s finished

####### Random_Forest #######
Score : 0.9800
[0.98079588 0.98028842 0.98159794 0.97920352 0.98001828]

MSE    : 318299.35 
MAE    : 277.90 
RMSE   : 564.18 
R2     : 0.979967 
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

####### DecisionTreeRegresor #######
Score : 0.9631
[0.9640538  0.96554851 0.96394078 0.96101075 0.965025

In [36]:
model_better = RandomForestRegressor()

In [37]:
model_better.fit(X_train,y_train)

y_pred=model_better.predict(X_test)

In [39]:
predictions = model_better.predict(X_test)
print(predictions)

[5754.85 3460.06  601.46 ...  509.35 5186.47 2289.82]


In [40]:
np.sqrt(mean_squared_error(y_test, predictions))

564.5516073030789

In [24]:
X_pred = pd.read_csv("diamonds_test.csv", index_col=0)
X_pred.head()

carat        cut color clarity  depth  table     x     y     z
0   0.30      Ideal     H     SI2   60.0   56.0  4.41  4.43  2.65
1   0.34      Ideal     D      IF   62.1   57.0  4.52  4.46  2.79
2   1.57  Very Good     I     VS2   60.3   58.0  7.58  7.55  4.56
3   0.31      Ideal     H     VS2   61.8   57.0  4.32  4.36  2.68
4   1.51       Good     I    VVS1   64.0   60.0  7.26  7.21  4.63

In [26]:
X_pred = X_pred.copy()
X_pred["clarity_value"] = X_pred["clarity"].map({'I1': 1, 'SI2': 2, 'SI1': 3, 'VS2':4, 'VS1':5, 'VVS2':6, 'VVS1':7, 'IF':8 })


In [27]:
X_pred["cut_value"] = X_pred["cut"].map({'Fair': 1, 'Good': 2, 'Very Good': 3, 'Premium':4, 'Ideal':5})

In [28]:
X_pred["color_value"] = X_pred["color"].map({'J': 1, 'I': 2, 'H': 3, 'G':4, 'F':5, 'E':6, 'D':7})
X_pred

carat        cut color clarity  depth  table     x     y     z  \
0       0.30      Ideal     H     SI2   60.0   56.0  4.41  4.43  2.65   
1       0.34      Ideal     D      IF   62.1   57.0  4.52  4.46  2.79   
2       1.57  Very Good     I     VS2   60.3   58.0  7.58  7.55  4.56   
3       0.31      Ideal     H     VS2   61.8   57.0  4.32  4.36  2.68   
4       1.51       Good     I    VVS1   64.0   60.0  7.26  7.21  4.63   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...   
13444   1.05      Ideal     F     SI2   60.3   55.0  6.55  6.68  3.99   
13445   0.27  Very Good     G     VS1   61.9   56.0  4.13  4.16  2.56   
13446   1.50    Premium     D     VS2   61.8   60.0  7.30  7.37  4.53   
13447   1.70    Premium     F     SI2   60.2   61.0  7.79  7.68  4.66   
13448   0.30      Ideal     D     VS2   61.2   57.0  4.29  4.34  2.64   

       clarity_value  cut_value  color_value  
0                  2          5            3  
1                  8          5            7  
2                  4          3            2  
3                  4          5            3  
4                  7          2            2  
...              ...        ...          ...  
13444              2          5            5  
13445              5          3            4  
13446              4          4            7  
13447              2          4            5  
13448              4          5            7  

[13449 rows x 12 columns]

In [29]:
X

array([[1.21, 6.73, 6.7 , ..., 4.  , 3.  , 5.  ],
       [0.28, 4.14, 4.17, ..., 6.  , 7.  , 3.  ],
       [0.42, 4.86, 4.82, ..., 5.  , 5.  , 4.  ],
       ...,
       [0.57, 5.33, 5.34, ..., 4.  , 2.  , 3.  ],
       [1.01, 6.47, 6.56, ..., 8.  , 5.  , 3.  ],
       [0.54, 5.33, 5.27, ..., 2.  , 6.  , 5.  ]])

In [30]:
X_pred = np.array(X_pred[['carat','x','y','z', 'clarity_value', 'color_value', 'cut_value']])

In [31]:
X_pred

array([[0.3 , 4.41, 4.43, ..., 2.  , 3.  , 5.  ],
       [0.34, 4.52, 4.46, ..., 8.  , 7.  , 5.  ],
       [1.57, 7.58, 7.55, ..., 4.  , 2.  , 3.  ],
       ...,
       [1.5 , 7.3 , 7.37, ..., 4.  , 7.  , 4.  ],
       [1.7 , 7.79, 7.68, ..., 2.  , 5.  , 4.  ],
       [0.3 , 4.29, 4.34, ..., 4.  , 7.  , 5.  ]])

In [41]:
predictions_submit = model_better.predict(X_pred)
predictions_submit

array([  425.49,  1814.41,  9557.95, ..., 15070.95, 10535.47,   768.38])

In [42]:
sample = pd.read_csv("sample_submission.csv")

In [43]:
submission = pd.DataFrame({"id": range(len(predictions_submit)), "price": predictions_submit})

In [44]:
submission.head()

id        price
0   0   425.490000
1   1  1814.410000
2   2  9557.950000
3   3   516.260952
4   4  8562.100000

In [45]:
def chequeator(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.
    
    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.
    
    Si no, LEE EL MENSAJE Y HAZLE CASO.
    
    Si aún no:
    - apaga tu ordenador, 
    - date una vuelta, 
    - enciendelo otra vez, 
    - abre este notebook y 
    - leelo todo de nuevo. 
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.id.all() == sample.id.all():
                print("You're ready to submit!")
                submission.to_csv("submission.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://i.kym-cdn.com/photos/images/facebook/000/747/556/27a.jpg", "gfg.png")     
                img = Image.open("gfg.png")
                img.show()   
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto de Clara: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `diamonds_test.csv`. Lloro.")


In [46]:
chequeator(submission)

You're ready to submit!


In [ ]:
# Apply the prediction model


def predict_model(X, y, model, test):
    model.fit(X, y)
    pred = model.predict(test)
    return pred

In [80]:
#reg_lin = LinearRegression()

rand_forest = RandomForestRegressor()

decis_tree =  DecisionTreeRegressor()


svr = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("selectkbest", SelectKBest()),
    ("svm", SVR())
])

knei_reg = KNeighborsRegressor()

grad_boos_reg =  GradientBoostingRegressor()

#reg_lin_param = {'alpha': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}

rand_forest_param = {
    'n_estimators': [10, 100, 1000],
    'max_features': [1,2,3]
}
knei_reg_param = {'n_neighbors': np.arange(1, 12, 2),
              'weights': ['uniform', 'distance']}

decis_tree_param = {'max_depth': np.arange(3, 10)} 
svr_param = {
    'selectkbest__k': [1,2,3],
    'svr__kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
    'svr__C': [0.001, 0.1, 0.5, 1, 5, 10],
    'svr__gamma': ('scale', 'auto')
    
}

grad_boos_reg_param = {'learning_rate': [0.01,0.02,0.03,0.04],
                  'subsample'    : [0.9, 0.5, 0.2, 0.1],
                  'n_estimators' : [100,500,1000, 1500],
                  'max_depth'    : [4,6,8,10]
                 }
cv = KFold(n_splits=10, random_state=1, shuffle=True )

#gs_reg_lin = GridSearchCV(reg_lin, reg_lin_param,
                        #param_grid = dict(alpha=reg_lin_param),
                         #cv = cv,
                         #scoring = 'MSE',
                         #verbose=1,
                         #n_jobs=-1)

gs_rand_forest = GridSearchCV(rand_forest,
                         rand_forest_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose=1,
                         n_jobs=-1)

gs_decis_tree = GridSearchCV(decis_tree, decis_tree_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose=1,
                         n_jobs=-1)

gs_svr = GridSearchCV(svr, svr_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose=1,
                         n_jobs=-1)

gs_knei_reg = GridSearchCV(knei_reg, knei_reg_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose=1,
                         n_jobs=-1)

gs_grad_boos_reg = GridSearchCV(grad_boos_reg, grad_boos_reg_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose=1,
                         n_jobs=-1)

grids = {"gs_rand_forest": gs_rand_forest, "gs_decis_tree": gs_decis_tree, "gs_svr": gs_svr, "gs_knei_reg": gs_knei_reg,"gs_grad_boos_reg": gs_grad_boos_reg }


In [81]:
%%time

for nombre, grid in grids.items():
    print("#################")
    print("NOMBRE:", nombre)
    print("#################")
    grid.fit(X_train, y_train)

#################
NOMBRE: gs_rand_forest
#################
Fitting 10 folds for each of 9 candidates, totalling 90 fits


In [ ]:
import pandas as pd
best_grids = [(i, j.best_score_) for i, j in grids.items()]

best_grids = pd.DataFrame(best_grids,
                         columns = ['Grid', 'Best score']).sort_values(by = 'Best score', ascending=False)
best_grids  