A partir de los datos de iris:

Ejercicio 1:

- Carga los datos originales
- Utiliza PCA para reducir la dimensionalidad de los datos. No reemplaces X con el resultado, crea una nueva X_pca. Utiliza PCA(2) y otra con PCA(3)
- Utiliza Kmeans para agrupar y predecir las clases de los nuevos datos.
- Compara los resultados para PCA(2) y PCA(3) con las clases originales (y_real).
- ¿Es mejor PCA(2) o PCA(3)?

Ejercicio 2: 

- Repite el proceso con T-SNE y DBSCAN. ¿Cuál da mejores resultados?


In [60]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target


Utiliza PCA para reducir la dimensionalidad de los datos. No reemplaces X con el resultado, crea una nueva X_pca. Utiliza PCA(2) y otra con PCA(3)

In [61]:
## reducir la dimensionalidad de los datos PCA(2)

from sklearn.decomposition import PCA

pca_2 = PCA(n_components=2)

X_pca_2 = pca_2.fit_transform(X)


In [62]:
X_train, X_test, y_train, y_test = train_test_split(X_pca_2,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

Utiliza Kmeans para agrupar y predecir las clases de los nuevos datos.

In [63]:
from sklearn.cluster import KMeans
k = 2
kmeans_2 = KMeans(n_clusters=k)
y_pred_2 = kmeans_2.fit_predict(X_train)
clusters = kmeans_2.cluster_centers_


In [64]:
print("\nkmeans.labels_:", kmeans_2.labels_)
print("predict:", y_pred_2)
print("kmeans.cluster_centers_:\n", clusters)


kmeans.labels_: [0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 1
 1 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1
 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 0 1 1 0 1 1]
predict: [0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 1
 1 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1
 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 0 1 1 0 1 1]
kmeans.cluster_centers_:
 [[-2.53014874  0.12194765]
 [ 1.34236055 -0.08778278]]


Compara los resultados para PCA(2) y PCA(3) con las clases originales (y_real).

In [65]:
kmeans_2.inertia_

110.03020207646931

In [66]:
kmeans_2.score(X_train)

-110.03020207646931

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_pred_2)

0.65

Compara los resultados para PCA(2) y PCA(3) con las clases originales (y_real).

In [68]:
y_pred = kmeans_2.predict(X_test)

In [69]:
import numpy as np
import pandas as pd

In [70]:
df_pred = pd.DataFrame({"digit":y_test, "prediction": y_pred})
df_pred["acierto"] = np.where(df_pred["digit"] == df_pred["prediction"], True, False)
df_pred

digit  prediction  acierto
0       1           1     True
1       0           0     True
2       2           1    False
3       1           1     True
4       1           1     True
5       0           0     True
6       1           1     True
7       2           1    False
8       1           1     True
9       1           1     True
10      2           1    False
11      0           0     True
12      0           0     True
13      0           0     True
14      0           0     True
15      1           1     True
16      2           1    False
17      1           1     True
18      1           1     True
19      2           1    False
20      0           0     True
21      2           1    False
22      0           0     True
23      2           1    False
24      2           1    False
25      2           1    False
26      2           1    False
27      2           1    False
28      0           0     True
29      0           0     True

In [71]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

In [72]:
## reducir la dimensionalidad de los datos PCA(3)

from sklearn.decomposition import PCA

pca_3 = PCA(n_components=3)

X_pca_3 = pca_3.fit_transform(X)

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_pca_3,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

In [73]:
from sklearn.cluster import KMeans
k = 3
kmeans_3 = KMeans(n_clusters=k)
y_pred_3 = kmeans_3.fit_predict(X_train)
clusters = kmeans_3.cluster_centers_

In [74]:
print("\nkmeans.labels_:", kmeans_3.labels_)
print("predict:", y_pred_3)
print("kmeans.cluster_centers_:\n", clusters)


kmeans.labels_: [0 0 2 0 0 2 2 0 0 0 2 2 2 0 0 2 2 1 2 1 2 1 2 0 1 2 0 0 0 2 2 0 0 0 2 0 2
 1 0 2 2 0 2 2 2 2 1 2 0 2 1 0 0 2 1 0 2 0 0 2 2 1 2 1 1 2 0 0 2 1 0 0 0 2
 1 0 1 1 0 2 2 2 1 1 0 1 2 1 2 2 2 0 2 2 0 2 1 1 0 2 1 1 0 1 0 1 1 1 2 1 2
 2 2 2 0 2 2 0 2 1]
predict: [0 0 2 0 0 2 2 0 0 0 2 2 2 0 0 2 2 1 2 1 2 1 2 0 1 2 0 0 0 2 2 0 0 0 2 0 2
 1 0 2 2 0 2 2 2 2 1 2 0 2 1 0 0 2 1 0 2 0 0 2 2 1 2 1 1 2 0 0 2 1 0 0 0 2
 1 0 1 1 0 2 2 2 1 1 0 1 2 1 2 2 2 0 2 2 0 2 1 1 0 2 1 1 0 1 0 1 1 1 2 1 2
 2 2 2 0 2 2 0 2 1]
kmeans.cluster_centers_:
 [[4.99       3.4525     1.45       0.245     ]
 [6.85517241 3.10344828 5.70689655 2.02068966]
 [5.85686275 2.73137255 4.38627451 1.44313725]]


### Compara los resultados para PCA(2) y PCA(3) con las clases originales (y_real).

In [75]:
kmeans_3.inertia_

64.88272836375931

In [76]:
kmeans_3.score(X_train)

-64.88272836375931

In [77]:
accuracy_score(y_train, y_pred_3)

0.4666666666666667

### Compara los resultados para PCA(2) y PCA(3) con las clases originales (y_real).

In [79]:
y_pred = kmeans_3.predict(X_test)
y_pred

array([2, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 2, 2, 1, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 0])

In [80]:
df_pred = pd.DataFrame({"digit":y_test, "prediction": y_pred })
df_pred["acierto"] = np.where(df_pred["digit"] == df_pred["prediction"], True, False)
df_pred

digit  prediction  acierto
0       1           2    False
1       0           0     True
2       2           1    False
3       1           2    False
4       1           2    False
5       0           0     True
6       1           2    False
7       2           1    False
8       1           2    False
9       1           2    False
10      2           1    False
11      0           0     True
12      0           0     True
13      0           0     True
14      0           0     True
15      1           2    False
16      2           1    False
17      1           2    False
18      1           2    False
19      2           1    False
20      0           0     True
21      2           2     True
22      0           0     True
23      2           1    False
24      2           1    False
25      2           1    False
26      2           1    False
27      2           1    False
28      0           0     True
29      0           0     True

¿Es mejor PCA(2) o PCA(3)?

In [ ]:
Ejercicio 2:

Repite el proceso con T-SNE y DBSCAN. ¿Cuál da mejores resultados?

In [4]:
from sklearn.manifold import TSNE
from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_samples, silhouette_score

In [102]:

iris = datasets.load_iris()
X = iris.data
y = iris.target


In [103]:
X_embedded = TSNE(n_components=2).fit_transform(X)
X_embedded.shape

(150, 2)

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X_embedded,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

In [105]:
db = DBSCAN(eps=0.55, min_samples=5)

In [106]:
y_preds = db.fit_predict(X_train)
y_preds

array([-1, -1, -1, -1, -1, -1, -1,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1,  0, -1,  1,  0,  0, -1, -1, -1, -1, -1, -1,
        1,  0,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1,  2, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  2, -1, -1, -1, -1,  2,
       -1, -1, -1, -1,  2, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        2], dtype=int64)

In [107]:
db.core_sample_indices_

array([  7,   8,  20,  23,  26,  34,  35,  69,  71, 108], dtype=int64)

In [109]:
n_clusters_ = len(set(y_preds)) - (1 if -1 in y_preds else 0)
n_noise_ = list(y_preds).count(-1)

print('Estimated number of clusters: %d' % n_clusters_)
print('Estimated number of noise points: %d' % n_noise_)
print("Homogeneity: %0.3f" % metrics.homogeneity_score(y_train, y_preds))
print("Completeness: %0.3f" % metrics.completeness_score(y_train, y_preds))
print("V-measure: %0.3f" % metrics.v_measure_score(y_train, y_preds))
print("Silhouette Coefficient: %0.3f"
      % metrics.silhouette_score(X_train, y_preds))


Estimated number of clusters: 3
Estimated number of noise points: 99
Homogeneity: 0.175
Completeness: 0.295
V-measure: 0.220
Silhouette Coefficient: -0.508


In [2]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target

In [5]:
X_embedded_3 = TSNE(n_components=3).fit_transform(X)
X_embedded_3.shape

(150, 3)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X_embedded_3,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

In [44]:
db = DBSCAN(eps=50, min_samples=4)

In [45]:
y_preds = db.fit_predict(X_train)
y_preds

array([-1, -1,  0, -1, -1,  0,  0,  1, -1, -1,  0,  0, -1, -1,  1,  0,  0,
       -1, -1,  2,  0,  2,  0,  1,  2,  0,  1, -1, -1,  0,  0, -1,  1,  1,
        0,  1,  0,  2,  1,  0,  0, -1,  0,  0,  0,  0, -1,  0, -1,  0,  0,
        1,  1,  0,  0,  1,  0,  1,  1,  0, -1, -1,  0,  0,  2,  0, -1, -1,
       -1,  2, -1,  1, -1,  0, -1, -1, -1, -1,  1,  0,  0,  0, -1, -1, -1,
       -1,  0,  0,  0,  0,  0, -1,  0,  0,  1,  0,  2, -1, -1,  0, -1,  2,
        1,  0, -1, -1,  2, -1,  0, -1, -1,  0,  0,  0, -1,  0, -1, -1, -1,
       -1], dtype=int64)

In [46]:
db.core_sample_indices_

array([  5,   6,   7,  10,  15,  16,  19,  20,  21,  23,  25,  29,  30,
        32,  34,  36,  38,  39,  40,  42,  43,  47,  49,  53,  56,  57,
        59,  62,  64,  71,  78,  79,  81,  86,  88,  89,  96,  99, 102,
       111, 112, 113, 115], dtype=int64)

In [47]:
n_clusters_ = len(set(y_preds)) - (1 if -1 in y_preds else 0)
n_noise_ = list(y_preds).count(-1)

print('Estimated number of clusters: %d' % n_clusters_)
print('Estimated number of noise points: %d' % n_noise_)
print("Homogeneity: %0.3f" % metrics.homogeneity_score(y_train, y_preds))
print("Completeness: %0.3f" % metrics.completeness_score(y_train, y_preds))
print("V-measure: %0.3f" % metrics.v_measure_score(y_train, y_preds))
print("Silhouette Coefficient: %0.3f"
      % metrics.silhouette_score(X_train, y_preds))

Estimated number of clusters: 3
Estimated number of noise points: 45
Homogeneity: 0.430
Completeness: 0.392
V-measure: 0.410
Silhouette Coefficient: 0.075


In [ ]:
fig, ax = plt.subplots(2, 1, figsize = (6, 8))
sns.scatterplot("sepal_length", "sepal_width", data = iris, hue = "species", ax = ax[0]);
sns.scatterplot("sepal_length", "sepal_width", data = iris, hue = "cluster",
                palette = "gist_stern", ax = ax[1]);

### El PCA con K-means da mejores resultados para esta base de datos 